export const FETCH_GROUP_BEGIN = "FETCH_GROUP_BEGIN";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";

export const FETCH_MESSAGES_BEGIN = "FETCH_MESSAGES_BEGIN";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";
export const FETCH_MESSAGES_RESET = "FETCH_MESSAGES_RESET";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";
export const RESET_MESSAGE_ADDED = "RESET_MESSAGE_ADDED";

export const SHOW_ALERT_MESSAGE = "SHOW_ALERT_MESSAGE";
export const HIDE_ALERT_MESSAGE = "HIDE_ALERT_MESSAGE";

export const FETCH_PROGRAM_BEGIN = "FETCH_PROGRAM_BEGIN";
export const FETCH_PROGRAM_LIST_SUCCESS = "FETCH_PROGRAM_LIST_SUCCESS";
export const FETCH_PROGRAM_SUCCESS = "FETCH_PROGRAM_SUCCESS";
export const FETCH_PROGRAM_FAILURE = "FETCH_PROGRAM_FAILURE";

export const FETCH_PLAN_BEGIN = "FETCH_PLAN_BEGIN";
export const FETCH_PLAN_LIST_SUCCESS = "FETCH_PLAN_LIST_SUCCESS";
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS";
export const FETCH_PLAN_FAILURE = "FETCH_PLAN_FAILURE";

export const CREATE_CALL_BEGIN = "CREATE_CALL_BEGIN";
export const CREATE_CALL_SUCCESS = "CREATE_CALL_SUCCESS";
export const CREATE_CALL_FAILURE = "CREATE_CALL_FAILURE";
export const CREATE_CALL_RESET = "CREATE_CALL_RESET";
