export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_SP_PROFILE_BEGIN = "FETCH_SERVICE_PROVIDER_PROFILE_BEGIN";
export const FETCH_SP_PROFILE_SUCCESS = "FETCH_SERVICE_PROVIDER_PROFILE_SUCCESS";
export const FETCH_SP_PROFILE_FAILURE = "FETCH_SERVICE_PROVIDER_PROFILE_FAILURE";
export const SAVE_SP_PROFILE_BEGIN = "SAVE_SERVICE_PROVIDER_PROFILE_BEGIN";
export const SAVE_SP_PROFILE_FAILURE = "SAVE_SERVICE_PROVIDER_PROFILE_FAILURE";
export const SAVE_SP_PROFILE_SUCCESS = "SAVE_SERVICE_PROVIDER_PROFILE_SUCCESS";


export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const FETCH_ADMIN_PROFILE_BEGIN = "FETCH_ADMIN_PROFILE_BEGIN";
export const FETCH_ADMIN_PROFILE_SUCCESS = "FETCH_ADMIN_PROFILE_SUCCESS";
export const FETCH_ADMIN_PROFILE_FAILURE = "FETCH_ADMIN_PROFILE_FAILURE";