export const LOGGED_IN = "LOGGED_IN";

export const SET_DIET_PLAN = "SET_DIET_PLAN";
export const ADD_DISHES_TO_MEAL = "ADD_DISHES_TO_MEAL";
export const ADD_DISH_TO_MEAL = "ADD_DISH_TO_MEAL";
export const DELETE_DISH_FROM_MEAL = "DELETE_DISH_FROM_MEAL";
export const SET_TRACK_STATUS_FOR_MEAL = "SET_TRACK_STATUS_FOR_MEAL";
export const REPLACE_DISH = "REPLACE_DISH";
export const DELETE_DISH = "DELETE_DISH";
export const CHANGE_DISH_QUANTITY = "CHANGE_DISH_QUANTITY";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const PROFILE_BEGIN = "PROFILE_BEGIN";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";
export const SAVE_PROFILE_FAILURE = "SAVE_PROFILE_FAILURE";

export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";
export const CHANGE_APP_TITLE = "CHANGE_APP_TITLE";

export const FETCH_DEPARTMENT_BEGIN = "DEPARTMENT_FETCH_BEGIN";
export const FETCH_ALL_DEPARTMENT_SUCCESS = "ALL_DEPARTMENT_FETCH_SUCCESS";
export const FETCH_ALL_DEPARTMENT_FAILURE = "ALL_DEPARTMENT_FETCH_FAILURE";
export const FETCH_CONSULTANCY_DEPARTMENT_SUCCESS =
  "CONSULTANCY_DEPARTMENT_FETCH_SUCCESS";
export const FETCH_CONSULTANCY_DEPARTMENT_FAILURE =
  "CONSULTANCY_DEPARTMENT_FETCH_FAILURE";

export const FETCH_CONSULTANTS_BEGIN = "FETCH_CONSULTANTS_BEGIN";
export const FETCH_CONSULTANTS_SUCCESS = "FETCH_CONSULTANTS_SUCCESS";
export const FETCH_CONSULTANTS_FAILURE = "FETCH_CONSULTANTS_FAILURE";

export const FETCH_SLOTS_BEGIN = "FETCH_SLOTS_BEGIN";
export const FETCH_SLOTS_SUCCESS = "FETCH_SLOTS_SUCCESS";
export const FETCH_SLOTS_FAILURE = "FETCH_SLOTS_FAILURE";

export const INIT_CONSULTATION_BEGIN = "INIT_CONSULTATION_BEGIN";
export const INIT_CONSULTATION_SUCCESS = "INIT_CONSULTATION_SUCCESS";
export const INIT_CONSULTATION_FETCH_SUCCESS =
  "INIT_CONSULTATION_FETCH_SUCCESS";
export const INIT_CONSULTATION_FAILURE = "INIT_CONSULTATION_FAILURE";

export const CAPTURE_PAYMENT_BEGIN = "CAPTURE_PAYMENT_BEGIN";
export const CAPTURE_PAYMENT_SUCCESS = "CAPTURE_PAYMENT_SUCCESS";
export const CAPTURE_PAYMENT_FAILURE = "CAPTURE_PAYMENT_FAILURE";

export const FETCH_CONSULTATIONS_LIST_BEGIN = "FETCH_CONSULTATIONS_LIST_BEGIN";
export const FETCH_CONSULTATIONS_LIST_SUCCESS =
  "FETCH_CONSULTATIONS_LIST_SUCCESS";
export const FETCH_CONSULTATIONS_LIST_FAILURE =
  "FETCH_CONSULTATIONS_LIST_FAILURE";

export const FETCH_GROUP_BEGIN = "FETCH_GROUP_BEGIN";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";

export const FETCH_MESSAGES_BEGIN = "FETCH_MESSAGES_BEGIN";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";
export const FETCH_MESSAGES_RESET = "FETCH_MESSAGES_RESET";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";
export const RESET_MESSAGE_ADDED = "RESET_MESSAGE_ADDED";

export const FETCH_COMMUNITY_POSTS_BEGIN = "FETCH_COMMUNITY_POSTS_BEGIN";
export const COMMUNITY_POSTS_RESET = "COMMUNITY_POSTS_RESET";
export const FETCH_COMMUNITY_POSTS_SUCCESS = "FETCH_COMMUNITY_POSTS_SUCCESS";
export const FETCH_COMMUNITY_POSTS_FAILURE = "FETCH_COMMUNITY_POSTS_FAILURE";
export const CREATE_COMMUNITY_POST_BEGIN = "CREATE_COMMUNITY_POST_BEGIN";
export const CREATE_COMMUNITY_POST_SUCCESS = "CREATE_COMMUNITY_POST_SUCCESS";
export const CREATE_COMMUNITY_POST_FAILURE = "CREATE_COMMUNITY_POST_FAILURE";
export const UPDATE_LIKE = "UPDATE_LIKE";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const SAVE_COMMENT_BEGIN = "SAVE_COMMENT_BEGIN";
export const SAVE_COMMENT = "SAVE_COMMENT";
export const SAVE_COMMENT_SUCCESS = "SAVE_COMMENT_SUCCESS";
export const FETCH_COMMUNITY_TAGS_BEGIN = "FETCH_COMMUNITY_TAGS_BEGIN";
export const FETCH_COMMUNITY_TAGS_SUCCESS = "FETCH_COMMUNITY_TAGS_SUCCESS";
export const FETCH_COMMUNITY_TAGS_FAILURE = "FETCH_COMMUNITY_TAGS_FAILURE";

export const PLAN_PURCHASE_BEGIN = "PLAN_PURCHASE_BEGIN";
export const PLAN_PURCHASE_SUCCESS = "PLAN_PURCHASE_SUCCESS";
export const PLAN_PURCHASE_FAILURE = "PLAN_PURCHASE_FAILURE";
export const PLAN_PURCHASE_RESET = "PLAN_PURCHASE_RESET";

export const FETCH_USER_PROGRAMS_BEGIN = "FETCH_USER_PROGRAMS_BEGIN";
export const FETCH_USER_PROGRAMS_SUCCESS = "FETCH_USER_PROGRAMS_SUCCESS";
export const FETCH_USER_PROGRAMS_FAILURE = "FETCH_USER_PROGRAMS_FAILURE";
export const ADD_USER_PROGRAM = "ADD_USER_PROGRAM";
export const UPDATE_USER_PROGRAM = "UPDATE_USER_PROGRAM";

export const FETCH_USER_PROGRAM_DIET_TRACKER_BEGIN =
  "FETCH_USER_PROGRAM_DIET_TRACKER_BEGIN";
export const FETCH_USER_PROGRAM_DIET_TRACKER_SUCCESS =
  "FETCH_USER_PROGRAM_DIET_TRACKER_SUCCESS";
export const FETCH_USER_PROGRAM_DIET_TRACKER_FAILURE =
  "FETCH_USER_PROGRAM_DIET_TRACKER_FAILURE";
export const ADD_USER_PROGRAM_DIET_CONSUMPTION =
  "ADD_USER_PROGRAM_DIET_CONSUMPTION";

export const FETCH_USER_PROGRAM_WORKOUT_TRACKER_BEGIN =
  "FETCH_USER_PROGRAM_WORKOUT_TRACKER_BEGIN";
export const FETCH_USER_PROGRAM_WORKOUT_TRACKER_SUCCESS =
  "FETCH_USER_PROGRAM_WORKOUT_TRACKER_SUCCESS";
export const FETCH_USER_PROGRAM_WORKOUT_TRACKER_FAILURE =
  "FETCH_USER_PROGRAM_WORKOUT_TRACKER_FAILURE";
export const ADD_USER_PROGRAM_WORKOUT_CONSUMPTION =
  "ADD_USER_PROGRAM_WORKOUT_CONSUMPTION";

export const FETCH_USER_PROGRAM_WEIGHT_TRACKER_BEGIN =
  "FETCH_USER_PROGRAM_WEIGHT_TRACKER_BEGIN";
export const FETCH_USER_PROGRAM_WEIGHT_TRACKER_SUCCESS =
  "FETCH_USER_PROGRAM_WEIGHT_TRACKER_SUCCESS";
export const FETCH_USER_PROGRAM_WEIGHT_TRACKER_FAILURE =
  "FETCH_USER_PROGRAM_WEIGHT_TRACKER_FAILURE";
export const ADD_USER_PROGRAM_WEIGHT = "ADD_USER_PROGRAM_WEIGHT";

export const FETCH_USER_PROGRAM_GOALS_BEGIN = "FETCH_USER_PROGRAM_GOALS_BEGIN";
export const FETCH_USER_PROGRAM_GOALS_SUCCESS =
  "FETCH_USER_PROGRAM_GOALS_SUCCESS";
export const FETCH_USER_PROGRAM_GOALS_FAILURE =
  "FETCH_USER_PROGRAM_GOALS_FAILURE";
