export const SW_INIT = 'SW_INIT';
export const SW_UPDATE = 'SW_UPDATE';

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_SP_PROFILE_BEGIN = "FETCH_SERVICE_PROVIDER_PROFILE_BEGIN";
export const FETCH_SP_PROFILE_SUCCESS = "FETCH_SERVICE_PROVIDER_PROFILE_SUCCESS";
export const FETCH_SP_PROFILE_FAILURE = "FETCH_SERVICE_PROVIDER_PROFILE_FAILURE";
export const SAVE_SP_PROFILE_BEGIN = "SAVE_SERVICE_PROVIDER_PROFILE_BEGIN";
export const SAVE_SP_PROFILE_FAILURE = "SAVE_SERVICE_PROVIDER_PROFILE_FAILURE";
export const SAVE_SP_PROFILE_SUCCESS = "SAVE_SERVICE_PROVIDER_PROFILE_SUCCESS";

export const FETCH_DEPARTMENTS_BEGIN = "FETCH_DEPARTMENTS_BEGIN";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";

export const FETCH_SCHEDULE_BEGIN = "FETCH_SCHEDULE_BEGIN";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILURE = "FETCH_SCHEDULE_FAILURE";
export const SAVE_SCHEDULE_BEGIN = "SAVE_SCHEDULE_BEGIN";
export const SAVE_SCHEDULE_SUCCESS = "SAVE_SCHEDULE_SUCCESS";
export const SAVE_SCHEDULE_FAILURE = "SAVE_SCHEDULE_FAILURE";

export const FETCH_GROUP_BEGIN = "FETCH_GROUP_BEGIN";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";

export const FETCH_MESSAGES_BEGIN = "FETCH_MESSAGES_BEGIN";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";
export const FETCH_MESSAGES_RESET = "FETCH_MESSAGES_RESET";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";
export const RESET_MESSAGE_ADDED = "RESET_MESSAGE_ADDED";

export const FETCH_USER_PROGRAMS_BEGIN = "FETCH_USER_PROGRAMS_BEGIN";
export const FETCH_USER_PROGRAMS_SUCCESS = "FETCH_USER_PROGRAMS_SUCCESS";
export const FETCH_USER_PROGRAMS_FAILURE = "FETCH_USER_PROGRAMS_FAILURE";
export const FETCH_USER_PROGRAMS_CLEAR = "FETCH_USER_PROGRAMS_CLEAR";